#ifndef _INCLUDE_CMANAGER_H
#define _INCLUDE_CMANAGER_H

/*
 * File generated by StormLink from mcc.fd
 * DO NOT EDIT
 * $VER: CManager.mcc 1.0 (17-Gen-99)
 */
#ifdef __cplusplus
extern "C" {
#endif
#pragma amicall(MCCBase, 0x1e, MCC_Query(d0))
#ifdef __cplusplus
};
#endif
#endif
