
all: GetEntry CMURL GetEntryNew

GetEntry: GetEntry.c
	gcc -o GetEntry GetEntry.c -I../include -noixemul

CMURL: CMURL.c
	gcc -o CMURL CMURL.c -I../include -noixemul

GetEntryNew: GetEntryNew.c
	gcc -o GetEntryNew GetEntryNew.c -I../include -noixemul
